name: Test Automation project

on:
  push:
    branches:
      - main
      - staging
      - develop
    paths:
      - '/**'
      - '.github/**'

concurrency:
  group: boyka-tests-${{ github.ref }}-1
  cancel-in-progress: true

env:
  BS_USER: ${{ secrets.BS_USER }}
  BS_KEY: ${{ secrets.BS_KEY }}
  LT_USER: ${{ secrets.LT_USER }}
  LT_KEY: ${{ secrets.LT_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          check-latest: true

      - name: Build the project
        run: mvn clean install -f pom.xml -DskipTests

  test-api:
    needs:
      - build
    uses: ./.github/workflows/_test-core-java.yml
    with:
      suite-name: testng-api

  test-others:
    needs:
      - build
    uses: ./.github/workflows/_test-core-java.yml
    with:
      suite-name: testng

  test-web-local:
    needs:
      - build
    uses: ./.github/workflows/_test-core-java.yml
    with:
      suite-name: testng-web
      runs-on: macos-latest

  test-web-bs:
    needs:
      - build
    uses: ./.github/workflows/_test-core-java.yml
    secrets:
      cloudUser: ${{ secrets.BS_USER }}
      cloudKey: ${{ secrets.BS_KEY }}
    with:
      suite-name: testng-web-bs

  test-web-lt:
    needs:
      - build
    uses: ./.github/workflows/_test-core-java.yml
    secrets:
      cloudUser: ${{ secrets.LT_USER }}
      cloudKey: ${{ secrets.LT_KEY }}
    with:
      suite-name: testng-web-lt

  test-mobile-bs:
    needs:
      - build
    uses: ./.github/workflows/_test-core-java.yml
    secrets:
      cloudUser: ${{ secrets.BS_USER }}
      cloudKey: ${{ secrets.BS_KEY }}
    with:
      suite-name: testng-android

  test-mobile-lt:
    needs:
      - build
    uses: ./.github/workflows/_test-core-java.yml
    secrets:
      cloudUser: ${{ secrets.LT_USER }}
      cloudKey: ${{ secrets.LT_KEY }}
    with:
      suite-name: testng-mobile-lt

  report:
    needs:
      - test-api
      - test-others
      - test-web-local
      - test-web-bs
      - test-web-lt
      - test-mobile-bs

    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
          check-latest: true

      - name: Download reports-testng-api files
        uses: actions/download-artifact@v3
        with:
          name: reports-testng-api
          path: /reports

      - name: Download reports-testng-mobile-bs files
        uses: actions/download-artifact@v3
        with:
          name: reports-testng-mobile-bs
          path: /reports

      - name: Download reports-testng-mobile-local files
        uses: actions/download-artifact@v3
        with:
          name: reports-testng-mobile-local
          path: /reports

      - name: Download reports-testng-mobile-web files
        uses: actions/download-artifact@v3
        with:
          name: reports-testng-mobile-web
          path: /reports

      - name: Download reports-testng-mobile-lt files
        uses: actions/download-artifact@v3
        with:
          name: reports-testng-mobile-lt
          path: /reports

      - name: Download reports-testng-others files
        uses: actions/download-artifact@v3
        with:
          name: reports-testng-others
          path: /reports

      - name: Download reports-testng-web-bs files
        uses: actions/download-artifact@v3
        with:
          name: reports-testng-web-bs
          path: /reports

      - name: Download reports-testng-web-grid files
        uses: actions/download-artifact@v3
        with:
          name: reports-testng-web-grid
          path: /reports

      - name: Download reports-testng-web-local files
        uses: actions/download-artifact@v3
        with:
          name: reports-testng-web-local
          path: /reports

      - name: Download reports-testng-web-lt files
        uses: actions/download-artifact@v3
        with:
          name: reports-testng-web-lt
          path: /reports

      - name: Generate Code Coverage Report
        run: |
          mvn verify org.jacoco:jacoco-maven-plugin:prepare-agent -f pom.xml -Pcoverage-report

      - name: Upload target folder
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: target-${{ github.run_id }}
          retention-days: 1
          path: |
            /target
            /logs
            /selenium-grid.log
            /screenshots

      - name: Upload reports folder
        uses: actions/upload-artifact@v3
        with:
          name: reports-${{ github.run_id }}
          retention-days: 1
          path: |
            /reports

  analysis:
    needs:
      - report
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          check-latest: true

      - name: Download target folder
        uses: actions/download-artifact@v3
        with:
          name: target-${{ github.run_id }}
          path: ${{ github.workspace }}

      - name: Download reports folder
        uses: actions/download-artifact@v3
        with:
          name: reports-${{ github.run_id }}
          path: ${{ github.workspace }}

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B sonar:sonar -f pom.xml -DskipTests -Dcheckstyle.skip
